### ISSUE TITLE
g++ error, several undefined reference to `xrt::

### ISSUE THREAD

**Issue by EnzoRafinesque** [Xilinx/Vitis-Tutorials#326]
Hi, 
I'm trying to follow the Vitis Getting Started tutorial and I encounter an issue in the part 4 : Build and Run the Data Center application,

I'm working on Ubuntu 20.04 and I've installed xrt for Vitis 2022.1 / Alveo U200 board following this : https://www.xilinx.com/products/boards-and-kits/alveo/u200.html#gettingStarted

The issue is on the command : `g++ -Wall -g -std=c++17 ../../src/host.cpp -o app.exe -I${XILINX_XRT}/include/ -L${XILINX_XRT}/lib/ -lOpenCL -lpthread -lrt -lstdc++`

and it return the following error : 

/usr/bin/ld: /tmp/ccjTQG0I.o: in function `main':
/home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:43: undefined reference to `xrt::device::load_xclbin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:48: undefined reference to `xrt::kernel::kernel(xrt::device const&, xrt::uuid const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, xrt::kernel::cu_access_mode)'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:51: undefined reference to `xrt::kernel::group_id(int) const'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:51: undefined reference to `xrt::device::operator void*() const'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:52: undefined reference to `xrt::kernel::group_id(int) const'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:52: undefined reference to `xrt::device::operator void*() const'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:53: undefined reference to `xrt::kernel::group_id(int) const'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:53: undefined reference to `xrt::device::operator void*() const'
/usr/bin/ld: /home/enzo/Desktop/workspace/Vitis-Tutorials/Getting_Started/Vitis/example/u200/sw_emu/../../src/host.cpp:78: undefined reference to `xrt::run::wait(std::chrono::duration<long, std::ratio<1l, 1000l> > const&) const'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `xrt::bo::bo(void*, unsigned long, unsigned int)':
/opt/xilinx/xrt/include/xrt/xrt_bo.h:187: undefined reference to `xrt::bo::bo(void*, unsigned long, xrt::bo::flags, unsigned int)'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `xrt::bo::sync(xclBOSyncDirection)':
/opt/xilinx/xrt/include/xrt/xrt_bo.h:393: undefined reference to `xrt::bo::size() const'
/usr/bin/ld: /opt/xilinx/xrt/include/xrt/xrt_bo.h:393: undefined reference to `xrt::bo::sync(xclBOSyncDirection, unsigned long, unsigned long)'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `xrt::device::device(int)':
/opt/xilinx/xrt/include/xrt/xrt_device.h:205: undefined reference to `xrt::device::device(unsigned int)'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `xrt::run::set_arg(int, xrt::bo&)':
/opt/xilinx/xrt/include/xrt/xrt_kernel.h:361: undefined reference to `xrt::run::set_arg_at_index(int, xrt::bo const&)'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `int* xrt::bo::map<int*>()':
/opt/xilinx/xrt/include/xrt/xrt_bo.h:420: undefined reference to `xrt::bo::map()'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `xrt::run xrt::kernel::operator()<xrt::bo&, xrt::bo&, xrt::bo&, int>(xrt::bo&, xrt::bo&, xrt::bo&, int&&)':
/opt/xilinx/xrt/include/xrt/xrt_kernel.h:633: undefined reference to `xrt::run::run(xrt::kernel const&)'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `void xrt::run::operator()<xrt::bo&, xrt::bo&, xrt::bo&, int>(xrt::bo&, xrt::bo&, xrt::bo&, int&&)':
/opt/xilinx/xrt/include/xrt/xrt_kernel.h:455: undefined reference to `xrt::run::start()'
/usr/bin/ld: /tmp/ccjTQG0I.o: in function `void xrt::run::set_arg<int>(int, int&&)':
/opt/xilinx/xrt/include/xrt/xrt_kernel.h:341: undefined reference to `xrt::run::set_arg_at_index(int, void const*, unsigned long)'
collect2: error: ld returned 1 exit status

I've searched on issues and other forums but I didn't found anything about that issue, if someone have an idea that will be helpful, thank you.

Best Regards,

Enzo.

**Comment by EnzoRafinesque** [comment]
From 2020.2 release XRT provides a new XRT API set in C, C++, and Python flavor.

To use the native XRT APIs, the host application must link with the xrt_coreutil library. Compiling host code with XRT native C++ API requires C++ standard with -std=c++17 (or newer).

add -lxrt_coreutil in the command to fix : 

g++ -Wall -g -std=c++17 ../../src/host.cpp -o app.exe -I${XILINX_XRT}/include/ -L${XILINX_XRT}/lib/ -lOpenCL -lpthread -lrt -lstdc++ -lxrt_coreutil
